application: blue-pear
version: 1
runtime: python27
api_version: 1

threadsafe: true

libraries:
- name: webapp2
  version: latest

builtins:
- remote_api: on

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /opentype_js
  static_dir: third_party/opentype_js

- url: /css
  static_dir: css

- url: /font_info\.html
  script: info.font_info.app

- url: /font_info/?
  script: info.font_info.app
  
- url: /font_compress\.html
  script: compress.font_compress.app

- url: /font_compress/?
  script: compress.font_compress.app
